name = "TilePyramids"
uuid = "dde2e3b5-1def-4180-bc9a-b7cbb52c3d29"
authors = ["Fabian Gans <fgans@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
